### ISSUE TITLE
v0.6.x ToDo

### ISSUE THREAD

**Issue by AlCap23** [SciML/DataDrivenDiffEq.jl#212]
There are some minor / major things still in need to figure out : 

- [ ] Implicit SINDy performs not as good as before
- [ ] Savitzky Golay filter implementation
- [ ] Koopman update might break 
- [ ] Properly work on the forcing term to include this reaaaaaally nice
- [ ] Implicit result transformation

But this can be done by future me, so I don't have to worry right now.
